name: Coolify Deploy
description: Reusable action for validating and triggering Coolify deployments with NTFY notifications
author: NasrDev

inputs:
  docker_image:
    description: The Docker image tag to display
    required: true
  ntfy_topic:
    description: NTFY topic to send notifications to
    required: false
  ntfy_token:
    description: NTFY authorization token (if topic is protected)
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate Coolify variables
      shell: bash
      run: |
        echo "Validating that COOLIFY_URL doesn't end in '/'"
        echo "$COOLIFY_URL" | grep -P '[^/]$'
        echo "Validating required environment variables are set"
        if [ -z "$COOLIFY_URL" ] || [ -z "$COOLIFY_RESOURCE_ID" ] || [ -z "$COOLIFY_API_TOKEN" ]; then
          echo "❌ Error: Missing required Coolify environment variables"
          exit 1
        fi

    - name: Update source commit SHA in Coolify
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ env.COOLIFY_URL }}/api/v1/applications/${{ env.COOLIFY_RESOURCE_ID }}
        method: PATCH
        bearerToken: ${{ env.COOLIFY_API_TOKEN }}
        data: >-
          {
            "git_commit_sha": "${{ github.sha }}"
          }

    - name: Trigger Coolify deployment via webhook
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ env.COOLIFY_URL }}/api/v1/deploy?uuid=${{ env.COOLIFY_RESOURCE_ID }}&force=false
        method: GET
        bearerToken: ${{ env.COOLIFY_API_TOKEN }}

    - name: Deployment status notification
      if: success()
      shell: bash
      run: |
        echo "✅ Deployment succeeded for ${{ inputs.docker_image }}"
        if [ -n "${{ inputs.ntfy_topic }}" ]; then
          curl -X POST \
            -H "Title: ✅ Coolify Deploy Success" \
            -H "Priority: 3" \
            -H "Tags: rocket" \
            -H "Authorization: Bearer ${{ inputs.ntfy_token }}" \
            -d "Deployment succeeded for ${{ inputs.docker_image }} (commit: ${{ github.sha }})" \
            https://ntfy.sh/${{ inputs.ntfy_topic }}
        fi

    - name: Deployment failure notification
      if: failure()
      shell: bash
      run: |
        echo "❌ Deployment failed for ${{ inputs.docker_image }}"
        if [ -n "${{ inputs.ntfy_topic }}" ]; then
          curl -X POST \
            -H "Title: ❌ Coolify Deploy Failed" \
            -H "Priority: 5" \
            -H "Tags: warning" \
            -H "Authorization: Bearer ${{ inputs.ntfy_token }}" \
            -d "Deployment failed for ${{ inputs.docker_image }} (commit: ${{ github.sha }})" \
            https://ntfy.sh/${{ inputs.ntfy_topic }}
        fi
